### ISSUE TITLE
`Invoke-FuzzyGetCmdlet` invokes but pre-fills the search

### ISSUE THREAD

**Issue by redactedscribe** [stinos/PsFzfLite#1]
When `Invoke-FuzzyGetCmdlet` invoke, its search input is pre-filled with the text "Invoke-FuzzyGetCmdlet". It should be empty to allow for immediate typing.

Thanks.

PsFzfLite c6ee2b0037fb099307310d585eada41f24b4af9b
fzf 0.37.0
PowerShell 7.3.2
Windows 11 Pro 22H2 10.0.22621

**Comment by stinos** [comment]
This is meant to be bound to a keyboard shortcut, like
```
Set-PSReadLineKeyHandler -Key 'ctrl-o' -BriefDescription 'Fuzzy cmdlet' -ScriptBlock { Invoke-FuzzyGetCmdlet -FzfArgs @('--preview', 'Get-Command {} -ShowCommandInfo') }
Set-PSReadLineKeyHandler -Key 'ctrl-shift-o' -BriefDescription 'Fuzzy any command' -ScriptBlock { Invoke-FuzzyGetCommand -FzfArgs @('--preview', '(Get-Command {}).Source') }
```
For example if you need the `Convert-ToJson` command you'd type `ctj` on the prompt followed by `Ctrl-o` and likely `Convert-ToJson` will be selected already in fzf as best match. Or you just hit `Ctrl-o` and start typing. Then after selecting something it will be inserted on the prompt at the location where the cursor was.
Perhaps I should add this explicitly in the readme.

I'm not sure if it's worth changing the Invoke-Fuzzy... functions so they can work when invoked from the prompt directly, that just seems to be too much typing :)

**Comment by redactedscribe** [comment]
Thanks for the example code. I've only recently installed fzf so I'm still in the process of learning how it all works. Knowing that the `Invoke-*` commands should be used via key-bindings helps (PsFzfLite is my first exposure to an fzf wrapper, so I had no previous PsFzf knowledge to go off). Maybe the README could make this more apparent to newcomers at some point.

**Comment by redactedscribe** [comment]
It's possible I'm still doing things wrong, but with the key-bindings applied, for `Invoke-FuzzyGetCmdlet` I'm getting:

```
The system cannot find the path specified.
'Get—Command' is not recognized as an internal or extern
operable program or batch file.
```

![1](https://user-images.githubusercontent.com/25013746/216976944-55fbec73-6ad5-4af2-87ff-f3d0ffd579da.png)

And for `Invoke-FuzzyGetCommand`:

```
The system cannot find the path specified.
.Source was unexpected at this time.
```

![2](https://user-images.githubusercontent.com/25013746/216976953-3e69dec4-4c81-42c4-801c-92a5dff71c8d.png)

But otherwise the key-bindings work as expected.

**Comment by stinos** [comment]
> The system cannot find the path specified.
'Get—Command' is not recognized as an internal or extern
operable program or batch file.

Sorry missed your reply; fzf invokes the preview handler via the shell, which defaults to `cmd` on windows whereas `Get-Command` is powershell. So to make this work you need to set the `SHELL` environment variable like `$env:SHELL='C:\tools\pwsh\pwsh.exe'` or similar. I'll check if I can clarify this in the readme.

**Comment by redactedscribe** [comment]
That fixed it, thanks. I'll have to remember `SHELL` now exists and is set in case anything else uses it.
