### ISSUE TITLE
Choosing a cmdlet from `Invoke-FuzzyGetCmdlet` doesn't produce output

### ISSUE THREAD

**Issue by redactedscribe** [stinos/PsFzfLite#2]
When invoking `Invoke-FuzzyGetCmdlet`, choosing a cmdlet doesn't appear to do anything. The cmdlet command will be added to PowerShell's CLI as text and be run(?) but it doesn't produce any output (if it's being run at all), only a new line for issuing your next command.

May be related to #1.

PsFzfLite c6ee2b0037fb099307310d585eada41f24b4af9b
fzf 0.37.0
PowerShell 7.3.2
Windows 11 Pro 22H2 10.0.22621

**Comment by stinos** [comment]
> May be related to https://github.com/stinos/PsFzfLite/issues/1.

Yes see explanation there
