### ISSUE TITLE
Any way to configure to make results prefer exact matches?

### ISSUE THREAD

**Issue by redactedscribe** [stinos/PsFzfLite#3]
With PowerShell's Ctrl+R, matches to are more useful when typing something accurate since there is no fuzzy matching. With PsFzfLite typing "usb" for example doesn't return even 1 exact match until I scroll much further up due to all the fuzzy matches. Ideally I'd see exact matches first, and then any fuzzy matches. This might fall under configuring fzf rather than PsFzfLite (newbie to fzf, sorry!). Do you know how/if this can be done?

Thanks.

**Comment by stinos** [comment]
Yeah this is standard fzf stuff, see https://github.com/junegunn/fzf#search-syntax
So in your case you're probably looking for `'usb`.

**Comment by redactedscribe** [comment]
Thanks, that was it! Now to find out if I can makes results ordered by exact and then fuzzy matches... Always typing `'` doesn't seem ideal, but perhaps I'll discover why it's set up this way. Thanks again.

---

For those interested, in your PowerShell PS1 profile:

```powershell
# PsFzfLite: Exact history search.
Set-PSReadLineKeyHandler -Key 'ctrl-r' -BriefDescription 'Fuzzy history' -ScriptBlock { Invoke-FuzzyHistory -FzfArgs @('--exact') }
# PsFzfLite: Fuzzy history search.
Set-PSReadLineKeyHandler -Key 'ctrl-shift-r' -BriefDescription 'Fuzzy history' -ScriptBlock { Invoke-FuzzyHistory }
```

**Comment by stinos** [comment]
> Now to find out if I can makes results ordered by exact and then fuzzy matches.

Not completely sure but I think the principle would be to first narrow the list with exact matches, then bind a key to use that list again as input and search it with fuzzy matches. Perhaps with the `reload` action or so.
